service: mx-beerhouse-subscription-webhook

frameworkVersion: '3'

plugins:
  - serverless-offline

custom:  
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}

functions:
  webhookDeleteSubs:
    handler: delete_subs.webhookDeleteSubs
    events:
      - httpApi:
         path: /webhook/delete-subs
         method: post
  webhookAddMpPaymentMethod:
    handler: create_mp_payment.webhookAddMpPaymentMethod
    events:
      - httpApi:
         path: /webhook/add-mp-payment-method
         method: post
         